### ISSUE TITLE
When an healthcheck fails then gets back up, it can stay on FAILING

### ISSUE THREAD

**Issue by Soulou** [Scalingo/link#58] opened 2019-07-17 15:55 UTC
```
Jul 17 15:50:10 ip-10-0-0-187 link[11230]: time="2019-07-17T15:50:10.657" level=error msg="Node failing" failing_count=21 id=vip-00825280-6ca3-4522-aca4-2b5057223bab ip=10.20.0.18/32 request_id=a9c22b05-f359-422f-8747-975e127ef1a9
Jul 17 15:50:10 ip-10-0-0-187 link[11230]: time="2019-07-17T15:50:10.658" level=error msg="Too many failure, setting status to failing" id=vip-00825280-6ca3-4522-aca4-2b5057223bab ip=10.20.0.18/32 request_id=a9c22b05-f359-422f-8747-975e12
Jul 17 15:50:20 ip-10-0-0-187 link[11230]: time="2019-07-17T15:50:20.658" level=error msg="Healthcheck failed" error="prober error: probe tcp: probe check failed: fail to open TCP connection: dial tcp 10.0.0.187:30118: i/o timeout" id=vip
Jul 17 15:50:20 ip-10-0-0-187 link[11230]: time="2019-07-17T15:50:20.658" level=error msg="Node failing" failing_count=22 id=vip-00825280-6ca3-4522-aca4-2b5057223bab ip=10.20.0.18/32 request_id=a9c22b05-f359-422f-8747-975e127ef1a9
Jul 17 15:50:20 ip-10-0-0-187 link[11230]: time="2019-07-17T15:50:20.659" level=error msg="Too many failure, setting status to failing" id=vip-00825280-6ca3-4522-aca4-2b5057223bab ip=10.20.0.18/32 request_id=a9c22b05-f359-422f-8747-975e12
Jul 17 15:50:29 ip-10-0-0-187 link[11230]: time="2019-07-17T15:50:29.803" level=info msg="starting request" from="10.0.0.254:35818" host="ip-10-0-0-187:1313" method=DELETE path=/ips/vip-00825280-6ca3-4522-aca4-2b5057223bab protocol=HTTP/1
Jul 17 15:50:29 ip-10-0-0-187 link[11230]: time="2019-07-17T15:50:29.804" level=info msg="request completed" bytes=0 duration=0.00017195 from="10.0.0.254:35818" host="ip-10-0-0-187:1313" method=DELETE path=/ips/vip-00825280-6ca3-4522-aca4
Jul 17 15:50:30 ip-10-0-0-187 link[11230]: time="2019-07-17T15:50:30.659" level=error msg="Healthcheck failed" error="prober error: probe tcp: probe check failed: fail to open TCP connection: dial tcp 10.0.0.187:30118: i/o timeout" id=vip
Jul 17 15:50:33 ip-10-0-0-187 link[11230]: time="2019-07-17T15:50:33.710" level=info msg="starting request" from="10.0.0.254:35818" host="ip-10-0-0-187:1313" method=POST path=/ips protocol=HTTP/1.1 request_id=8143e925-07c6-47f9-a08c-ea43c
Jul 17 15:50:33 ip-10-0-0-187 link[11230]: time="2019-07-17T15:50:33.724" level=info msg="Cancel manager stopping" id=vip-00825280-6ca3-4522-aca4-2b5057223bab ip=10.20.0.18/32 request_id=8143e925-07c6-47f9-a08c-ea43c0034006
```

**Comment by johnsudaar** [comment] 2019-07-17 19:11
Duplicate of #57

**Closed by johnsudaar** 2019-07-17 19:11 UTC
